services:
  r_uber_bot:
    container_name: r_uber_bot
    image: uber/r_uber_bot:1.0.0
    build:
      context: ./bot
      dockerfile: rust.dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      # - ./dbdata:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
